# Shared script derivations used by both:
#   - the darwin module (installed into environment.systemPackages)
#   - the flake's apps + packages outputs (for `nix run` / `nix shell`)
#
# Single source of truth so the module surface and the CLI surface never drift.
#
# Deploys agentic-community/mcp-gateway-registry locally on macOS:
# docker compose (upstream's blessed path) inside a Colima VM. The stack's
# scripts mutate their own checkout (.env, .oauth-tokens/), so we manage a
# writable working clone rather than a nix-store source.

{ pkgs
, workDirDefault ? "$HOME/mcp-gateway-registry"
, repoUrl ? "https://github.com/agentic-community/mcp-gateway-registry"
, repoRef ? "main"
, vmCpus ? 4
, vmMemoryGiB ? 8
, vmDiskGiB ? 60
}:

let
  # Python with huggingface_hub for the one-time embedding model download
  # (sentence-transformers/all-MiniLM-L6-v2, ~90MB, runs on CPU in-container).
  pythonHf = pkgs.python3.withPackages (ps: [ ps.huggingface-hub ]);

  mkScript = name: text: pkgs.writeShellApplication {
    inherit name text;
    runtimeInputs = with pkgs; [
      docker colima git curl jq openssl coreutils gnused gnugrep pythonHf
    ];
  };

  # The default may contain $HOME on purpose — it expands in the *user's*
  # shell at runtime, keeping the system-level module usable for any user.
  workdirPreamble = ''
    WORKDIR="''${MCPGW_WORKDIR:-${workDirDefault}}"
  '';
in
{
  # ------------------------------------------------------------------
  # mcpgw-install: one-time (idempotent) setup of the working clone
  # ------------------------------------------------------------------
  mcpgw-install = mkScript "mcpgw-install" ''
    ${workdirPreamble}
    REPO_URL="''${MCPGW_REPO_URL:-${repoUrl}}"
    REPO_REF="''${MCPGW_REPO_REF:-${repoRef}}"

    # 1. Clone or update the upstream repo (a writable checkout is required:
    #    build_and_run.sh generates secrets into .env and the Keycloak setup
    #    writes .oauth-tokens/ inside the tree).
    if [ -d "$WORKDIR/.git" ]; then
      echo "==> Updating existing clone at $WORKDIR ($REPO_REF)"
      git -C "$WORKDIR" fetch --tags origin "$REPO_REF"
      git -C "$WORKDIR" checkout "$REPO_REF"
      git -C "$WORKDIR" pull --ff-only origin "$REPO_REF" 2>/dev/null || true
    else
      echo "==> Cloning $REPO_URL ($REPO_REF) to $WORKDIR"
      git clone --branch "$REPO_REF" "$REPO_URL" "$WORKDIR"
    fi

    # 2. Seed .env from .env.example with strong generated secrets.
    #    build_and_run.sh auto-generates most secrets, but hard-fails a
    #    preflight denylist check on these five if left at placeholders.
    if [ ! -f "$WORKDIR/.env" ]; then
      echo "==> Seeding .env with generated credentials"
      cp "$WORKDIR/.env.example" "$WORKDIR/.env"

      gen() { openssl rand -base64 24 | tr -d '/+='; }
      KC_ADMIN_PW="$(gen)"; KC_DB_PW="$(gen)"; GRAFANA_PW="$(gen)"; USER_PW="$(gen)"

      setenv() { sed -i "s|^$1=.*|$1=$2|" "$WORKDIR/.env"; }
      setenv KEYCLOAK_ADMIN_PASSWORD "$KC_ADMIN_PW"
      setenv KEYCLOAK_DB_PASSWORD    "$KC_DB_PW"
      setenv GRAFANA_ADMIN_PASSWORD  "$GRAFANA_PW"
      # Upstream expects INITIAL_ADMIN_PASSWORD == KEYCLOAK_ADMIN_PASSWORD
      setenv INITIAL_ADMIN_PASSWORD  "$KC_ADMIN_PW"
      setenv INITIAL_USER_PASSWORD   "$USER_PW"

      # Keep a human-readable record next to the other local secrets
      CREDS="$HOME/.config/secrets/mcp-gateway-credentials"
      mkdir -p "$(dirname "$CREDS")"
      {
        echo "# Generated by mcpgw-install on $(date '+%Y-%m-%d %H:%M')"
        echo "KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PW   # user: admin (Keycloak + registry UI)"
        echo "GRAFANA_ADMIN_PASSWORD=$GRAFANA_PW"
        echo "INITIAL_USER_PASSWORD=$USER_PW"
      } > "$CREDS"
      chmod 600 "$CREDS"
      echo "    Credentials recorded in $CREDS"
    else
      echo "==> .env already exists — leaving it untouched"
    fi

    # 3. Embedding model for FAISS semantic search. The compose bind-mounts
    #    $HOME/mcp-gateway/models; the registry only *warns* if it's missing
    #    and you'd get a running-but-broken search.
    MODEL_DIR="$HOME/mcp-gateway/models/all-MiniLM-L6-v2"
    if [ ! -f "$MODEL_DIR/config.json" ]; then
      echo "==> Downloading embedding model to $MODEL_DIR (~90MB)"
      python -c "from huggingface_hub import snapshot_download; snapshot_download('sentence-transformers/all-MiniLM-L6-v2', local_dir='$MODEL_DIR')"
    else
      echo "==> Embedding model already present"
    fi

    echo
    echo "✓ Install complete. Next: mcpgw-up, then (first time only) mcpgw-bootstrap."
  '';

  # ------------------------------------------------------------------
  # mcpgw-up: Colima VM + prebuilt stack
  # ------------------------------------------------------------------
  mcpgw-up = mkScript "mcpgw-up" ''
    ${workdirPreamble}
    if [ ! -d "$WORKDIR" ]; then
      echo "No working clone at $WORKDIR — run mcpgw-install first." >&2
      exit 1
    fi

    # Friendly warning: RKE2 (nix-k8s-lima) + this stack both want ~8GB.
    if limactl list --json 2>/dev/null | jq -e 'select(.name=="rke2" and .status=="Running")' >/dev/null 2>&1; then
      echo "⚠ RKE2 Lima VM is running — both VMs want ~8GB RAM. Consider 'rke2-stop' first."
    fi

    # VM sizing only applies on first creation; later starts reuse it.
    # NOTE: recreating the VM (colima delete) wipes docker volumes —
    # Keycloak realm and MongoDB data — and requires mcpgw-bootstrap again.
    if ! colima status >/dev/null 2>&1; then
      echo "==> Starting Colima (${toString vmCpus} CPU / ${toString vmMemoryGiB}GB RAM / ${toString vmDiskGiB}GB disk)"
      colima start --cpus ${toString vmCpus} --memory ${toString vmMemoryGiB} --disk ${toString vmDiskGiB}
    fi

    # Upstream's prepare-log-dirs.sh sudo-chowns /var/log/containers on the
    # *mac*, but under Colima the bind-mount source resolves inside the VM —
    # the host-side prep is pointless here and would sudo-prompt on every
    # start. Disable it (build_and_run.sh skips non-executable scripts with
    # a warning) and do the equivalent inside the VM, where sudo is
    # passwordless. Containers run as uid 1000 and need write access.
    cd "$WORKDIR"
    chmod -x scripts/prepare-log-dirs.sh 2>/dev/null || true

    # Bind-mount sources the upstream repo doesn't ship on a fresh clone.
    # The VM's docker daemon can't create them through the home-dir mount
    # (chown fails), so make sure they exist host-side first.
    mkdir -p keycloak/themes keycloak/providers

    colima ssh -- sudo sh -c \
      'mkdir -p /var/log/containers/ai-registry && chown -R 1000:1000 /var/log/containers/ai-registry && chmod 750 /var/log/containers/ai-registry'

    # Upstream's blessed entry point; --prebuilt pulls multi-arch images
    # from public.ecr.aws instead of building. It ends with an interactive
    # "follow the logs?" read that would poison the exit code when stdin
    # isn't a TTY — feed it a "n".
    printf 'n\n' | ./build_and_run.sh --prebuilt

    echo
    echo "✓ Stack started. First time? Run mcpgw-bootstrap to initialize Keycloak."
    echo "  Registry UI: http://localhost   (admin / see ~/.config/secrets/mcp-gateway-credentials)"
  '';

  # ------------------------------------------------------------------
  # mcpgw-bootstrap: one-time Keycloak realm/client/user initialization
  # ------------------------------------------------------------------
  mcpgw-bootstrap = mkScript "mcpgw-bootstrap" ''
    ${workdirPreamble}
    cd "$WORKDIR"

    echo "==> [1/4] Creating Keycloak realm, clients and groups"
    bash keycloak/setup/init-keycloak.sh

    echo "==> [2/4] Retrieving generated client secrets"
    bash keycloak/setup/get-all-client-credentials.sh

    # The credentials file is KEY=VALUE format; merge the two client
    # secrets into .env (compose passes them to auth-server/registry).
    SECRETS_FILE=".oauth-tokens/keycloak-client-secrets.txt"
    for key in KEYCLOAK_CLIENT_SECRET KEYCLOAK_M2M_CLIENT_SECRET; do
      val="$(grep "^$key=" "$SECRETS_FILE" | tail -1 | cut -d= -f2-)"
      if [ -z "$val" ]; then
        echo "Could not find $key in $SECRETS_FILE" >&2; exit 1
      fi
      sed -i "s|^$key=.*|$key=$val|" .env
    done
    echo "==> Client secrets merged into .env"

    echo "==> [3/4] Restarting stack with the new secrets"
    # (trailing "follow the logs?" prompt answered with n — see mcpgw-up)
    printf 'n\n' | ./build_and_run.sh --prebuilt

    echo "==> [4/4] Creating admin user and M2M service accounts"
    bash cli/bootstrap_user_and_m2m_setup.sh

    echo
    echo "✓ Bootstrap complete — log in at http://localhost"
  '';

  # ------------------------------------------------------------------
  # Lifecycle helpers
  # ------------------------------------------------------------------
  mcpgw-down = mkScript "mcpgw-down" ''
    ${workdirPreamble}
    cd "$WORKDIR"
    docker compose -f docker-compose.prebuilt.yml down --remove-orphans
    echo "✓ Stack stopped (data volumes preserved). 'colima stop' to also stop the VM."
  '';

  mcpgw-status = mkScript "mcpgw-status" ''
    ${workdirPreamble}
    echo "── Colima VM ──────────────────────────────────────────"
    colima status 2>&1 || true
    echo
    echo "── Containers ─────────────────────────────────────────"
    if [ -d "$WORKDIR" ]; then
      (cd "$WORKDIR" && docker compose -f docker-compose.prebuilt.yml ps 2>/dev/null) \
        || echo "(stack not running)"
    else
      echo "(not installed — run mcpgw-install)"
    fi
    echo
    echo "── URLs ───────────────────────────────────────────────"
    echo "  Registry UI     http://localhost"
    echo "  Keycloak admin  http://localhost:8080  (user: admin)"
    echo "  Grafana         http://localhost:3000"
    echo "  Prometheus      http://localhost:9090"
    echo "  Credentials     ~/.config/secrets/mcp-gateway-credentials"
  '';

  mcpgw-delete = mkScript "mcpgw-delete" ''
    ${workdirPreamble}
    cd "$WORKDIR"
    echo "This DESTROYS all stack data (MongoDB, Keycloak realm, Grafana)."
    read -r -p "Type 'yes' to continue: " ans
    [ "$ans" = "yes" ] || { echo "Aborted."; exit 1; }
    docker compose -f docker-compose.prebuilt.yml down --remove-orphans --volumes
    echo "✓ Stack and volumes deleted. Re-run mcpgw-up + mcpgw-bootstrap to start fresh."
    echo "  (The clone, .env and credentials file were kept; delete $WORKDIR to remove them.)"
  '';

  mcpgw-help = mkScript "mcpgw-help" ''
    cat <<'HELP_EOF'
MCP Gateway Registry — local stack (Colima + docker compose, arm64 native)

  First-time setup:
    mcpgw-install     clone repo, generate secrets, download embedding model
    mcpgw-up          start Colima VM + the 8-container prebuilt stack
    mcpgw-bootstrap   initialize Keycloak (realm, clients, admin user)

  Daily use:
    mcpgw-up / mcpgw-down     start / stop the stack
    mcpgw-status              VM + container status, URLs
    mcpgw-delete              wipe all data volumes (asks for confirmation)

  Load testing: see the companion flake (nix-mcp-gateway-k6) for the
  mcpgw-k6-* commands and the Grafana load dashboard.

  Where things live:
    working clone   $MCPGW_WORKDIR (default: ~/mcp-gateway-registry)
    credentials     ~/.config/secrets/mcp-gateway-credentials
    embedding model ~/mcp-gateway/models/all-MiniLM-L6-v2

  Notes:
    * Runs in the Colima docker VM (~8GB) — don't run alongside the RKE2
      Lima VM on a 16GB machine ('rke2-stop' first).
    * Recreating the Colima VM wipes docker volumes (Keycloak realm,
      MongoDB) — re-run mcpgw-bootstrap afterwards.
    * Overrides: MCPGW_WORKDIR, MCPGW_REPO_URL, MCPGW_REPO_REF.
HELP_EOF
  '';
}
